DROP DATABASE IF EXISTS todo;

CREATE DATABASE todo;

USE todo;

CREATE TABLE task (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255) NOT NULL
);

INSERT INTO TASK (DESCRIPTION) VALUES ('MY TEST TASK');
INSERT INTO TASK (DESCRIPTION) VALUES ('MY ANOTHER TEST TASK');
